#ifndef SERIALCONTROLCPP_GLOBAL_H
#define SERIALCONTROLCPP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERIALCONTROLCPP_LIBRARY)
#  define SERIALCONTROLCPPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SERIALCONTROLCPPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SERIALCONTROLCPP_GLOBAL_H
